// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AsrTask.proto

package com.example.protobuf.testprotobuf;

public final class AsrTaskOuterClass {
  private AsrTaskOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AsrTaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:testprotobuf.AsrTask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 taskId = 1;</code>
     */
    long getTaskId();

    /**
     * <pre>
     *测试数据集id
     * </pre>
     *
     * <code>int64 tsiId = 2;</code>
     */
    long getTsiId();

    /**
     * <code>string url = 3;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>string url = 3;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>string text = 4;</code>
     */
    java.lang.String getText();
    /**
     * <code>string text = 4;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>string appKey = 5;</code>
     */
    java.lang.String getAppKey();
    /**
     * <code>string appKey = 5;</code>
     */
    com.google.protobuf.ByteString
        getAppKeyBytes();

    /**
     * <code>int32 dictation = 6;</code>
     */
    int getDictation();

    /**
     * <code>string wsUrl = 7;</code>
     */
    java.lang.String getWsUrl();
    /**
     * <code>string wsUrl = 7;</code>
     */
    com.google.protobuf.ByteString
        getWsUrlBytes();
  }
  /**
   * Protobuf type {@code testprotobuf.AsrTask}
   */
  public  static final class AsrTask extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:testprotobuf.AsrTask)
      AsrTaskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AsrTask.newBuilder() to construct.
    private AsrTask(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AsrTask() {
      url_ = "";
      text_ = "";
      appKey_ = "";
      wsUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AsrTask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              taskId_ = input.readInt64();
              break;
            }
            case 16: {

              tsiId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              appKey_ = s;
              break;
            }
            case 48: {

              dictation_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              wsUrl_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.protobuf.testprotobuf.AsrTaskOuterClass.internal_static_testprotobuf_AsrTask_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.protobuf.testprotobuf.AsrTaskOuterClass.internal_static_testprotobuf_AsrTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask.class, com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask.Builder.class);
    }

    public static final int TASKID_FIELD_NUMBER = 1;
    private long taskId_;
    /**
     * <code>int64 taskId = 1;</code>
     */
    public long getTaskId() {
      return taskId_;
    }

    public static final int TSIID_FIELD_NUMBER = 2;
    private long tsiId_;
    /**
     * <pre>
     *测试数据集id
     * </pre>
     *
     * <code>int64 tsiId = 2;</code>
     */
    public long getTsiId() {
      return tsiId_;
    }

    public static final int URL_FIELD_NUMBER = 3;
    private volatile java.lang.Object url_;
    /**
     * <code>string url = 3;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEXT_FIELD_NUMBER = 4;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 4;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPKEY_FIELD_NUMBER = 5;
    private volatile java.lang.Object appKey_;
    /**
     * <code>string appKey = 5;</code>
     */
    public java.lang.String getAppKey() {
      java.lang.Object ref = appKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appKey_ = s;
        return s;
      }
    }
    /**
     * <code>string appKey = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAppKeyBytes() {
      java.lang.Object ref = appKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DICTATION_FIELD_NUMBER = 6;
    private int dictation_;
    /**
     * <code>int32 dictation = 6;</code>
     */
    public int getDictation() {
      return dictation_;
    }

    public static final int WSURL_FIELD_NUMBER = 7;
    private volatile java.lang.Object wsUrl_;
    /**
     * <code>string wsUrl = 7;</code>
     */
    public java.lang.String getWsUrl() {
      java.lang.Object ref = wsUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wsUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string wsUrl = 7;</code>
     */
    public com.google.protobuf.ByteString
        getWsUrlBytes() {
      java.lang.Object ref = wsUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wsUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (taskId_ != 0L) {
        output.writeInt64(1, taskId_);
      }
      if (tsiId_ != 0L) {
        output.writeInt64(2, tsiId_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, url_);
      }
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, text_);
      }
      if (!getAppKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, appKey_);
      }
      if (dictation_ != 0) {
        output.writeInt32(6, dictation_);
      }
      if (!getWsUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, wsUrl_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (taskId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, taskId_);
      }
      if (tsiId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, tsiId_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, url_);
      }
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, text_);
      }
      if (!getAppKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, appKey_);
      }
      if (dictation_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, dictation_);
      }
      if (!getWsUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, wsUrl_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask)) {
        return super.equals(obj);
      }
      com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask other = (com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask) obj;

      if (getTaskId()
          != other.getTaskId()) return false;
      if (getTsiId()
          != other.getTsiId()) return false;
      if (!getUrl()
          .equals(other.getUrl())) return false;
      if (!getText()
          .equals(other.getText())) return false;
      if (!getAppKey()
          .equals(other.getAppKey())) return false;
      if (getDictation()
          != other.getDictation()) return false;
      if (!getWsUrl()
          .equals(other.getWsUrl())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTaskId());
      hash = (37 * hash) + TSIID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTsiId());
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (37 * hash) + APPKEY_FIELD_NUMBER;
      hash = (53 * hash) + getAppKey().hashCode();
      hash = (37 * hash) + DICTATION_FIELD_NUMBER;
      hash = (53 * hash) + getDictation();
      hash = (37 * hash) + WSURL_FIELD_NUMBER;
      hash = (53 * hash) + getWsUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code testprotobuf.AsrTask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:testprotobuf.AsrTask)
        com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.protobuf.testprotobuf.AsrTaskOuterClass.internal_static_testprotobuf_AsrTask_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.protobuf.testprotobuf.AsrTaskOuterClass.internal_static_testprotobuf_AsrTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask.class, com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask.Builder.class);
      }

      // Construct using com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        taskId_ = 0L;

        tsiId_ = 0L;

        url_ = "";

        text_ = "";

        appKey_ = "";

        dictation_ = 0;

        wsUrl_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.protobuf.testprotobuf.AsrTaskOuterClass.internal_static_testprotobuf_AsrTask_descriptor;
      }

      @java.lang.Override
      public com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask getDefaultInstanceForType() {
        return com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask build() {
        com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask buildPartial() {
        com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask result = new com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask(this);
        result.taskId_ = taskId_;
        result.tsiId_ = tsiId_;
        result.url_ = url_;
        result.text_ = text_;
        result.appKey_ = appKey_;
        result.dictation_ = dictation_;
        result.wsUrl_ = wsUrl_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask) {
          return mergeFrom((com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask other) {
        if (other == com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask.getDefaultInstance()) return this;
        if (other.getTaskId() != 0L) {
          setTaskId(other.getTaskId());
        }
        if (other.getTsiId() != 0L) {
          setTsiId(other.getTsiId());
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        if (!other.getAppKey().isEmpty()) {
          appKey_ = other.appKey_;
          onChanged();
        }
        if (other.getDictation() != 0) {
          setDictation(other.getDictation());
        }
        if (!other.getWsUrl().isEmpty()) {
          wsUrl_ = other.wsUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long taskId_ ;
      /**
       * <code>int64 taskId = 1;</code>
       */
      public long getTaskId() {
        return taskId_;
      }
      /**
       * <code>int64 taskId = 1;</code>
       */
      public Builder setTaskId(long value) {
        
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 taskId = 1;</code>
       */
      public Builder clearTaskId() {
        
        taskId_ = 0L;
        onChanged();
        return this;
      }

      private long tsiId_ ;
      /**
       * <pre>
       *测试数据集id
       * </pre>
       *
       * <code>int64 tsiId = 2;</code>
       */
      public long getTsiId() {
        return tsiId_;
      }
      /**
       * <pre>
       *测试数据集id
       * </pre>
       *
       * <code>int64 tsiId = 2;</code>
       */
      public Builder setTsiId(long value) {
        
        tsiId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *测试数据集id
       * </pre>
       *
       * <code>int64 tsiId = 2;</code>
       */
      public Builder clearTsiId() {
        
        tsiId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>string url = 3;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string url = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 3;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 3;</code>
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 3;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 4;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 4;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 4;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 4;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appKey_ = "";
      /**
       * <code>string appKey = 5;</code>
       */
      public java.lang.String getAppKey() {
        java.lang.Object ref = appKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appKey = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAppKeyBytes() {
        java.lang.Object ref = appKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appKey = 5;</code>
       */
      public Builder setAppKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appKey = 5;</code>
       */
      public Builder clearAppKey() {
        
        appKey_ = getDefaultInstance().getAppKey();
        onChanged();
        return this;
      }
      /**
       * <code>string appKey = 5;</code>
       */
      public Builder setAppKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appKey_ = value;
        onChanged();
        return this;
      }

      private int dictation_ ;
      /**
       * <code>int32 dictation = 6;</code>
       */
      public int getDictation() {
        return dictation_;
      }
      /**
       * <code>int32 dictation = 6;</code>
       */
      public Builder setDictation(int value) {
        
        dictation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dictation = 6;</code>
       */
      public Builder clearDictation() {
        
        dictation_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object wsUrl_ = "";
      /**
       * <code>string wsUrl = 7;</code>
       */
      public java.lang.String getWsUrl() {
        java.lang.Object ref = wsUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          wsUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string wsUrl = 7;</code>
       */
      public com.google.protobuf.ByteString
          getWsUrlBytes() {
        java.lang.Object ref = wsUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          wsUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string wsUrl = 7;</code>
       */
      public Builder setWsUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        wsUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string wsUrl = 7;</code>
       */
      public Builder clearWsUrl() {
        
        wsUrl_ = getDefaultInstance().getWsUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string wsUrl = 7;</code>
       */
      public Builder setWsUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        wsUrl_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:testprotobuf.AsrTask)
    }

    // @@protoc_insertion_point(class_scope:testprotobuf.AsrTask)
    private static final com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask();
    }

    public static com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AsrTask>
        PARSER = new com.google.protobuf.AbstractParser<AsrTask>() {
      @java.lang.Override
      public AsrTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AsrTask(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AsrTask> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AsrTask> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.protobuf.testprotobuf.AsrTaskOuterClass.AsrTask getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_testprotobuf_AsrTask_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_testprotobuf_AsrTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rAsrTask.proto\022\014testprotobuf\"u\n\007AsrTask" +
      "\022\016\n\006taskId\030\001 \001(\003\022\r\n\005tsiId\030\002 \001(\003\022\013\n\003url\030\003" +
      " \001(\t\022\014\n\004text\030\004 \001(\t\022\016\n\006appKey\030\005 \001(\t\022\021\n\tdi" +
      "ctation\030\006 \001(\005\022\r\n\005wsUrl\030\007 \001(\tB#\n!com.exam" +
      "ple.protobuf.testprotobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_testprotobuf_AsrTask_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_testprotobuf_AsrTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_testprotobuf_AsrTask_descriptor,
        new java.lang.String[] { "TaskId", "TsiId", "Url", "Text", "AppKey", "Dictation", "WsUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
